### PR TITLE
Compile Libnotify & enable notification access

### PR DESCRIPTION
**Pull request by MTRNord**
This is an alternative approach to the same thing #15 solves.

The major difference here is that the smaller SDK can be used.

(Note: At the time of writing, this was not tested locally)

### CODE REVIEW

**Comment by Mikaela** [comment]
The test build above (https://github.com/flathub/org.briarproject.Briar/pull/16#issuecomment-1435000353) resolves the issue.

I am commenting in case no one else tested it.

**Comment by muelli** [comment]
Excellent, thanks!

I wonder whether there are any headers that could be cleaned up, though. It probably leaves more behind than the plain .so.

**Comment by muelli** [comment]
and does the .desktop file need a change, too?

**Comment by MTRNord** [comment]
I will double check but based on the matrix chat that's linked from the other pr I believe it should be added too.

**Comment by MTRNord** [comment]
> and does the .desktop file need a change, too?

Followed up in #18

**Pull request merged**
